server:
  port: 8081

spring:
  application:
    name: user-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true

info:
  app:
    name: AegisOps User Service
    version: 0.1.0
